### ISSUE TITLE
坐标点问题困惑

### ISSUE THREAD

**Issue by zcdliuwei** [cereslibra/TurtleAndFourier#3]
您好，看了您的DrawManyTurtle.py代码，受益匪浅，画图过程也非常有趣，您代码中使用的数据文件：datas0.txt到datas3.txt，似乎没有看到这几个文件是如何生成的，所以有些困惑，希望能得到您的解答，非常感谢。

**Comment by hibcz** [comment]
有点回复的太晚了，但还是说一下吧。
1、将你要画的图的svg格式（矢量图形）文件的代码直接复制出来这里以ai的导出举例：
![svg格式的代码导出](https://github.com/cereslibra/TurtleAndFourier/assets/161228263/9f54f5d7-14de-4523-85eb-4e17ee6bc38e)
2、复制svg代码并且替换rawvertexes.txt（此项目代码倒数第二个）中的内容并保存。
3、将FourierMath.py（此项目代码第四个）与rawvertexes.txt放在同一文件夹下运行前者，会生成你需要的data文件，自己改变名称为datas0.txt到datas3.txt即可
